apiVersion: v1
kind: Service
metadata:
  name: {{ include "cassandra.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "cassandra.labels" . | nindent 4 }}

  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: cql
      port: {{ .Values.service.port }}
      targetPort: cql
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.cql)) }}
      nodePort: {{ .Values.service.nodePorts.cql }}
      {{- else if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.metrics)) }}
      nodePort: {{ .Values.service.nodePorts.metrics }}
      {{- else if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
  selector:
    {{- include "cassandra.selectorLabels" . | nindent 4 }}